# Translations template for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
# Bruno Cornec <bruno.cornec@hp.com>, 2014
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-09-19 06:36+0000\n"
"PO-Revision-Date: 2014-09-17 17:40+0000\n"
"Last-Translator: Bruno Cornec <bruno.cornec@hp.com>\n"
"Language-Team: French (http://www.transifex.com/projects/p/keystone/language/"
"fr/)\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: keystone/notifications.py:176
#, python-format
msgid "Method not callable: %s"
msgstr "Impossible d'appeler la méthode %s"

#: keystone/catalog/core.py:60
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr "Noeud final incorrect %(url)s - clé inconnue %(keyerror)s"

#: keystone/catalog/core.py:65
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""
"Noeud final incorrect '%(url)s'. L'erreur suivante est survenue pendant la "
"substitution de chaine : %(typeerror)s"

#: keystone/catalog/core.py:71
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type notifier ?)"
msgstr ""
"Noeud final incorrect '%s - Format incomplet (un type de notification manque-"
"t-il ?)"

#: keystone/common/openssl.py:90
#, python-format
msgid "Command %(to_exec)s exited with %(retcode)s- %(output)s"
msgstr "La commande %(to_exec)s a retourné %(retcode)s- %(output)s"

#: keystone/common/environment/eventlet_server.py:100
#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr "Impossible de s'attacher à %(host)s:%(port)s"

#: keystone/contrib/endpoint_policy/core.py:129
#: keystone/contrib/endpoint_policy/core.py:228
#, python-format
msgid ""
"Circular reference or a repeated entry found in region tree - %(region_id)s."
msgstr ""
"Référence circulaire ou entrée dupliquée trouvée dans l'arbre de la région - "
"%(region_id)s."

#: keystone/contrib/federation/idp.py:404
#, python-format
msgid "Error when signing assertion, reason: %(reason)s"
msgstr "Erreur lors de la signature d'une assertion : %(reason)s"

#: keystone/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Exception d'origine en cours de suppression : %s"

#: keystone/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Exception inattendue survenue %d fois... Nouvel essai."

#: keystone/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "dans l'appel en boucle de durée fixe"

#: keystone/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "dans l'appel en boucle dynamique"

#: keystone/openstack/common/policy.py:508
#, python-format
msgid "Failed to understand rule %s"
msgstr "Règle %s incompréhensible"

#: keystone/openstack/common/policy.py:518
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Aucun gestionnaire pour les correspondances de type %s"

#: keystone/openstack/common/policy.py:788
#, python-format
msgid "Failed to understand rule %r"
msgstr "Règle %r incompréhensible"

#: keystone/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Exception pendant le nettoyage rpc."

#: keystone/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Exception non gérée"
