# Translations template for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
msgid ""
msgstr ""
"Project-Id-Version: Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-09-07 06:06+0000\n"
"PO-Revision-Date: 2014-06-20 20:11+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Portuguese (Brazil) (http://www.transifex.com/projects/p/"
"keystone/language/pt_BR/)\n"
"Language: pt_BR\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"
"Plural-Forms: nplurals=2; plural=(n > 1);\n"

#: keystone/notifications.py:176
#, python-format
msgid "Method not callable: %s"
msgstr ""

#: keystone/catalog/core.py:56
#, python-format
msgid "Malformed endpoint %(url)s - unknown key %(keyerror)s"
msgstr ""

#: keystone/catalog/core.py:61
#, python-format
msgid ""
"Malformed endpoint '%(url)s'. The following type error occurred during "
"string substitution: %(typeerror)s"
msgstr ""

#: keystone/catalog/core.py:67
#, python-format
msgid ""
"Malformed endpoint %s - incomplete format (are you missing a type notifier ?)"
msgstr ""

#: keystone/common/openssl.py:90
#, python-format
msgid "Command %(to_exec)s exited with %(retcode)s- %(output)s"
msgstr ""

#: keystone/common/environment/eventlet_server.py:100
#, python-format
msgid "Could not bind to %(host)s:%(port)s"
msgstr ""

#: keystone/contrib/endpoint_policy/core.py:129
#: keystone/contrib/endpoint_policy/core.py:228
#, python-format
msgid ""
"Circular reference or a repeated entry found in region tree - %(region_id)s."
msgstr ""

#: keystone/contrib/federation/idp.py:404
#, python-format
msgid "Error when signing assertion, reason: %(reason)s"
msgstr ""

#: keystone/openstack/common/excutils.py:76
#, python-format
msgid "Original exception being dropped: %s"
msgstr "Exceção original sendo descartada: %s"

#: keystone/openstack/common/excutils.py:105
#, python-format
msgid "Unexpected exception occurred %d time(s)... retrying."
msgstr "Exceção não esperada ocorreu %d vez(es)... tentando novamente."

#: keystone/openstack/common/loopingcall.py:95
msgid "in fixed duration looping call"
msgstr "em uma chamada de laço de duração fixa"

#: keystone/openstack/common/loopingcall.py:138
msgid "in dynamic looping call"
msgstr "em chamada de laço dinâmico"

#: keystone/openstack/common/policy.py:508
#, python-format
msgid "Failed to understand rule %s"
msgstr "Falha ao interpretar regra %s"

#: keystone/openstack/common/policy.py:518
#, python-format
msgid "No handler for matches of kind %s"
msgstr "Nenhum manipulador para correspondências do tipo %s"

#: keystone/openstack/common/policy.py:788
#, python-format
msgid "Failed to understand rule %r"
msgstr "Falha ao interpretar regra %r"

#: keystone/openstack/common/service.py:188
msgid "Exception during rpc cleanup."
msgstr "Exceção durante limpeza de RPC."

#: keystone/openstack/common/service.py:277
msgid "Unhandled exception"
msgstr "Exceção não tratada"
