# Portuguese (Brazil) translations for keystone.
# Copyright (C) 2014 OpenStack Foundation
# This file is distributed under the same license as the keystone project.
#
# Translators:
# Gabriel Wainer, 2013
# vmoliveira <volmar.oliveira.jr@gmail.com>, 2013
msgid ""
msgstr ""
"Project-Id-Version:  Keystone\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/keystone\n"
"POT-Creation-Date: 2014-10-07 14:35+0000\n"
"PO-Revision-Date: 2014-04-19 01:30+0000\n"
"Last-Translator: openstackjenkins <jenkins@openstack.org>\n"
"Language-Team: Portuguese (Brazil) "
"(http://www.transifex.com/projects/p/keystone/language/pt_BR/)\n"
"Plural-Forms: nplurals=2; plural=(n > 1)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 1.3\n"

#: keystone/clean.py:24
#, python-format
msgid "%s cannot be empty."
msgstr "%s não pode estar vazio."

#: keystone/clean.py:26
#, python-format
msgid "%(property_name)s cannot be less than %(min_length)s characters."
msgstr "%(property_name)s não pode ter menos de %(min_length)s caracteres."

#: keystone/clean.py:31
#, python-format
msgid "%(property_name)s should not be greater than %(max_length)s characters."
msgstr "%(property_name)s não deve ter mais de %(max_length)s caracteres."

#: keystone/clean.py:40
#, python-format
msgid "%(property_name)s is not a %(display_expected_type)s"
msgstr "%(property_name)s não é um %(display_expected_type)s"

#: keystone/cli.py:141
msgid "keystone-manage pki_setup is not recommended for production use."
msgstr ""

#: keystone/cli.py:160
msgid "keystone-manage ssl_setup is not recommended for production use."
msgstr ""

#: keystone/cli.py:218
msgid "At least one option must be provided"
msgstr ""

#: keystone/cli.py:225
msgid "--all option cannot be mixed with other options"
msgstr ""

#: keystone/cli.py:234
#, python-format
msgid "Unknown domain '%(name)s' specified by --domain-name"
msgstr ""

#: keystone/exception.py:49
msgid "missing exception kwargs (programmer error)"
msgstr "ausente exceção kwargs (erro do programador)"

#: keystone/exception.py:79
#, python-format
msgid ""
"Expecting to find %(attribute)s in %(target)s - the server could not "
"comply with the request since it is either malformed or otherwise "
"incorrect. The client is assumed to be in error."
msgstr ""

#: keystone/exception.py:90
#, python-format
msgid "%(detail)s"
msgstr ""

#: keystone/exception.py:94
msgid ""
"Timestamp not in expected format. The server could not comply with the "
"request since it is either malformed or otherwise incorrect. The client "
"is assumed to be in error."
msgstr ""
"A data não está no formato especificado. O servidor não pôde realizar a "
"requisição pois ela está mal formada ou incorreta. Assume-se que o "
"cliente está com erro."

#: keystone/exception.py:103
#, python-format
msgid ""
"String length exceeded.The length of string '%(string)s' exceeded the "
"limit of column %(type)s(CHAR(%(length)d))."
msgstr ""
"Comprimento de string excedido. O comprimento de string '%(string)s' "
"excedeu o limite da coluna %(type)s(CHAR(%(length)d))."

#: keystone/exception.py:109
#, python-format
msgid ""
"Request attribute %(attribute)s must be less than or equal to %(size)i. "
"The server could not comply with the request because the attribute size "
"is invalid (too large). The client is assumed to be in error."
msgstr ""
"Atributo de requisição %(attribute)s deve ser menor ou igual a %(size)i. "
"O servidor não pôde atender a requisição porque o tamanho do atributo é "
"inválido (muito grande). Assume-se que o cliente está em erro."

#: keystone/exception.py:119
#, python-format
msgid ""
"The password length must be less than or equal to %(size)i. The server "
"could not comply with the request because the password is invalid."
msgstr ""

#: keystone/exception.py:127
#, python-format
msgid ""
"Unable to delete region %(region_id)s because it or its child regions "
"have associated endpoints."
msgstr ""

#: keystone/exception.py:134
msgid ""
"The certificates you requested are not available. It is likely that this "
"server does not use PKI tokens otherwise this is the result of "
"misconfiguration."
msgstr ""

#: keystone/exception.py:143
msgid "(Disable debug mode to suppress these details.)"
msgstr ""

#: keystone/exception.py:148
#, python-format
msgid "%(message)s %(amendment)s"
msgstr ""

#: keystone/exception.py:156
msgid "The request you have made requires authentication."
msgstr "A requisição que você fez requer autenticação."

#: keystone/exception.py:162
msgid "Authentication plugin error."
msgstr "Erro do plugin de autenticação."

#: keystone/exception.py:170
#, python-format
msgid "Unable to find valid groups while using mapping %(mapping_id)s"
msgstr ""

#: keystone/exception.py:175
msgid "Attempted to authenticate with an unsupported method."
msgstr "Tentativa de autenticação com um método não suportado."

#: keystone/exception.py:183
msgid "Additional authentications steps required."
msgstr "Passos de autenticação adicionais requeridos."

#: keystone/exception.py:191
msgid "You are not authorized to perform the requested action."
msgstr "Você não está autorizado à realizar a ação solicitada."

#: keystone/exception.py:198
#, python-format
msgid "You are not authorized to perform the requested action: %(action)s"
msgstr ""

#: keystone/exception.py:203
#, python-format
msgid ""
"Could not change immutable attribute(s) '%(attributes)s' in target "
"%(target)s"
msgstr ""

#: keystone/exception.py:208
#, python-format
msgid ""
"Group membership across backend boundaries is not allowed, group in "
"question is %(group_id)s, user is %(user_id)s"
msgstr ""

#: keystone/exception.py:214
#, python-format
msgid ""
"Invalid mix of entities for policy association - only Endpoint, Service "
"or Region+Service allowed. Request was - Endpoint: %(endpoint_id)s, "
"Service: %(service_id)s, Region: %(region_id)s"
msgstr ""

#: keystone/exception.py:221
#, python-format
msgid "Could not find: %(target)s"
msgstr ""

#: keystone/exception.py:227
#, python-format
msgid "Could not find endpoint: %(endpoint_id)s"
msgstr ""

#: keystone/exception.py:234
msgid "An unhandled exception has occurred: Could not find metadata."
msgstr "Uma exceção não tratada ocorreu: Não foi possível encontrar metadados."

#: keystone/exception.py:239
#, python-format
msgid "Could not find policy: %(policy_id)s"
msgstr ""

#: keystone/exception.py:243
msgid "Could not find policy association"
msgstr ""

#: keystone/exception.py:247
#, python-format
msgid "Could not find role: %(role_id)s"
msgstr ""

#: keystone/exception.py:251
#, python-format
msgid "Could not find region: %(region_id)s"
msgstr ""

#: keystone/exception.py:255
#, python-format
msgid "Could not find service: %(service_id)s"
msgstr ""

#: keystone/exception.py:259
#, python-format
msgid "Could not find domain: %(domain_id)s"
msgstr ""

#: keystone/exception.py:263
#, python-format
msgid "Could not find project: %(project_id)s"
msgstr ""

#: keystone/exception.py:267
#, python-format
msgid "Could not find token: %(token_id)s"
msgstr ""

#: keystone/exception.py:271
#, python-format
msgid "Could not find user: %(user_id)s"
msgstr ""

#: keystone/exception.py:275
#, python-format
msgid "Could not find group: %(group_id)s"
msgstr ""

#: keystone/exception.py:279
#, python-format
msgid "Could not find mapping: %(mapping_id)s"
msgstr ""

#: keystone/exception.py:283
#, python-format
msgid "Could not find trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:287
#, python-format
msgid "No remaining uses for trust: %(trust_id)s"
msgstr ""

#: keystone/exception.py:291
#, python-format
msgid "Could not find credential: %(credential_id)s"
msgstr ""

#: keystone/exception.py:295
#, python-format
msgid "Could not find version: %(version)s"
msgstr ""

#: keystone/exception.py:299
#, python-format
msgid "Could not find Endpoint Group: %(endpoint_group_id)s"
msgstr ""

#: keystone/exception.py:303
#, python-format
msgid "Could not find Identity Provider: %(idp_id)s"
msgstr ""

#: keystone/exception.py:307
#, python-format
msgid ""
"Could not find federated protocol %(protocol_id)s for Identity Provider: "
"%(idp_id)s"
msgstr ""

#: keystone/exception.py:318
#, python-format
msgid "Conflict occurred attempting to store %(type)s - %(details)s"
msgstr ""

#: keystone/exception.py:325
msgid "Request is too large."
msgstr "Requisição é muito grande."

#: keystone/exception.py:332
msgid "An unexpected error prevented the server from fulfilling your request."
msgstr ""

#: keystone/exception.py:335
#, python-format
msgid ""
"An unexpected error prevented the server from fulfilling your request: "
"%(exception)s"
msgstr ""

#: keystone/exception.py:358
#, python-format
msgid "Unable to consume trust %(trust_id)s, unable to acquire lock."
msgstr ""

#: keystone/exception.py:363
msgid ""
"Expected signing certificates are not available on the server. Please "
"check Keystone configuration."
msgstr ""

#: keystone/exception.py:369
#, python-format
msgid "Malformed endpoint URL (%(endpoint)s), see ERROR log for details."
msgstr ""
"URL de endpoint mal-formada (%(endpoint)s), veja o log de ERROS para "
"detalhes."

#: keystone/exception.py:374
#, python-format
msgid ""
"Group %(group_id)s returned by mapping %(mapping_id)s was not found in "
"the backend."
msgstr ""

#: keystone/exception.py:379
#, python-format
msgid "Error while reading metadata file, %(reason)s"
msgstr ""

#: keystone/exception.py:383
msgid "The action you have requested has not been implemented."
msgstr "A ação que você solicitou não foi implementada."

#: keystone/exception.py:390
msgid "The service you have requested is no longer available on this server."
msgstr ""

#: keystone/exception.py:397
#, python-format
msgid "The Keystone configuration file %(config_file)s could not be found."
msgstr ""

#: keystone/exception.py:402
#, python-format
msgid ""
"The Keystone domain configuration file %(config_file)s defines an "
"additional SQL driver - only one is permitted."
msgstr ""

#: keystone/exception.py:409
#, python-format
msgid ""
"%(mod_name)s doesn't provide database migrations. The migration "
"repository path at %(path)s doesn't exist or isn't a directory."
msgstr ""

#: keystone/exception.py:421
#, python-format
msgid ""
"Unable to sign SAML assertion. It is likely that this server does not "
"have xmlsec1 installed, or this is the result of misconfiguration. Reason"
" %(reason)s"
msgstr ""

#: keystone/notifications.py:167
#, python-format
msgid "%(event)s is not a valid notification event, must be one of: %(actions)s"
msgstr ""

#: keystone/notifications.py:223
msgid "Failed to construct notifier"
msgstr ""

#: keystone/notifications.py:267
#, python-format
msgid "Failed to send %(res_id)s %(event_type)s notification"
msgstr "Falha ao enviar notificação %(res_id)s %(event_type)s"

#: keystone/notifications.py:455
#, python-format
msgid "Failed to send %(action)s %(event_type)s notification"
msgstr ""

#: keystone/assignment/controllers.py:77
#, python-format
msgid "Authentication failed: %s"
msgstr "Autenticação falhou: %s"

#: keystone/assignment/controllers.py:110
#: keystone/assignment/controllers.py:224 keystone/identity/controllers.py:67
msgid "Name field is required and cannot be empty"
msgstr "Campo nome é requerido e não pode ser vazio"

#: keystone/assignment/controllers.py:165
msgid "Marker could not be found"
msgstr "Marcador não pôde ser encontrado"

#: keystone/assignment/controllers.py:176
msgid "Invalid limit value"
msgstr "Valor limite inválido"

#: keystone/assignment/controllers.py:479
msgid "Specify a domain or project, not both"
msgstr "Especifique um domínio ou projeto, não ambos"

#: keystone/assignment/controllers.py:484
msgid "Specify a user or group, not both"
msgstr "Epecifique um usuário ou grupo, não ambos"

#: keystone/assignment/controllers.py:712
#, python-format
msgid ""
"Group %(group)s not found for role-assignment - %(target)s with Role: "
"%(role)s"
msgstr ""
"Grupo %(group)s não encontrado para a atribuição de role - %(target)s com"
" Role: %(role)s"

#: keystone/assignment/core.py:103 keystone/token/core.py:72
#: keystone/token/core.py:88
#, python-format
msgid "Domain is disabled: %s"
msgstr "O domínio está desativado: %s"

#: keystone/assignment/core.py:114
#, python-format
msgid "Project is disabled: %s"
msgstr "O projeto está desativado: %s"

#: keystone/assignment/core.py:325
msgid "Multiple domains are not supported"
msgstr ""

#: keystone/assignment/core.py:385
msgid "delete the default domain"
msgstr ""

#: keystone/assignment/core.py:396
msgid "cannot delete a domain that is enabled, please disable it first."
msgstr ""

#: keystone/assignment/core.py:616
#, python-format
msgid "Project (%s)"
msgstr "Projeto (%s)"

#: keystone/assignment/core.py:618
#, python-format
msgid "Domain (%s)"
msgstr "Domínio (%s)"

#: keystone/assignment/core.py:620
msgid "Unknown Target"
msgstr "Alvo Desconhecido"

#: keystone/assignment/core.py:1106 keystone/common/controller.py:286
#: keystone/identity/core.py:330
#, python-format
msgid "Expected dict or list: %s"
msgstr "Esperado dict ou list: %s"

#: keystone/assignment/backends/kvs.py:257
#: keystone/assignment/backends/ldap.py:551
#: keystone/assignment/backends/sql.py:405
#, python-format
msgid "Cannot remove role that has not been granted, %s"
msgstr "Não é possível remover role que não foi concedido, %s"

#: keystone/assignment/backends/ldap.py:119
msgid "Domain metadata not supported by LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:215
#: keystone/assignment/backends/ldap.py:259 keystone/catalog/core.py:100
#: keystone/common/ldap/core.py:1378 keystone/identity/backends/kvs.py:120
#: keystone/identity/backends/kvs.py:225
#, python-format
msgid "Duplicate ID, %s."
msgstr "ID duplicado, %s."

#: keystone/assignment/backends/ldap.py:223 keystone/common/ldap/core.py:1368
#: keystone/identity/backends/kvs.py:128 keystone/identity/backends/kvs.py:155
#: keystone/identity/backends/kvs.py:232 keystone/identity/backends/kvs.py:260
#, python-format
msgid "Duplicate name, %s."
msgstr "Nome duplicado, %s."

#: keystone/assignment/backends/ldap.py:261
#: keystone/assignment/backends/ldap.py:269
#: keystone/assignment/backends/ldap.py:273
msgid "Domains are read-only against LDAP"
msgstr ""

#: keystone/assignment/backends/ldap.py:313
#: keystone/assignment/backends/sql.py:145
msgid "Inherited roles can only be assigned to domains"
msgstr "Roles herdados podem ser atribuídos somente à domínios"

#: keystone/assignment/backends/ldap.py:530
#, python-format
msgid "User %(user_id)s already has role %(role_id)s in tenant %(tenant_id)s"
msgstr ""

#: keystone/assignment/backends/ldap.py:536
#, python-format
msgid "Role %s not found"
msgstr "Role %s não localizada"

#: keystone/assignment/backends/ldap.py:647
#, python-format
msgid "Cannot duplicate name %s"
msgstr ""

#: keystone/assignment/backends/sql.py:132
#, python-format
msgid ""
"Unexpected combination of grant attributes - User, Group, Project, "
"Domain: %s"
msgstr ""

#: keystone/assignment/backends/sql.py:323
msgid "Must specify either domain or project"
msgstr ""

#: keystone/assignment/backends/sql.py:426
#, python-format
msgid "Unexpected assignment type encountered, %s"
msgstr ""

#: keystone/auth/controllers.py:60
#, python-format
msgid ""
"Cannot load an auth-plugin by class-name without a \"method\" attribute "
"defined: %s"
msgstr ""

#: keystone/auth/controllers.py:71
#, python-format
msgid ""
"Auth plugin %(plugin)s is requesting previously registered method "
"%(method)s"
msgstr ""

#: keystone/auth/controllers.py:115
#, python-format
msgid ""
"Unable to reconcile identity attribute %(attribute)s as it has "
"conflicting values %(new)s and %(old)s"
msgstr ""

#: keystone/auth/controllers.py:332
msgid "Scoping to both domain and project is not allowed"
msgstr "A definição de escopo para o domínio e o projeto não é permitida"

#: keystone/auth/controllers.py:335
msgid "Scoping to both domain and trust is not allowed"
msgstr "A definição de escopo para o domínio e a trust não é permitida"

#: keystone/auth/controllers.py:338
msgid "Scoping to both project and trust is not allowed"
msgstr "A definição de escopo para o projeto e a trust não é permitida"

#: keystone/auth/controllers.py:441
#, python-format
msgid ""
"User %(user_id)s doesn't have access to default project %(project_id)s. "
"The token will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:448
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s is disabled. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:457
#, python-format
msgid ""
"User %(user_id)s's default project %(project_id)s not found. The token "
"will be unscoped rather than scoped to the project."
msgstr ""

#: keystone/auth/controllers.py:503
msgid "User not found"
msgstr "Usuário não localizado"

#: keystone/auth/controllers.py:613
msgid "A project-scoped token is required to produce a service catalog."
msgstr ""

#: keystone/auth/plugins/external.py:46
msgid "No authenticated user"
msgstr "Nenhum usuário autenticado"

#: keystone/auth/plugins/external.py:56
#, python-format
msgid "Unable to lookup user %s"
msgstr "Não é possível consultar o usuário %s"

#: keystone/auth/plugins/external.py:107
msgid "auth_type is not Negotiate"
msgstr ""

#: keystone/auth/plugins/oauth1.py:39
#, python-format
msgid "%s not supported"
msgstr ""

#: keystone/auth/plugins/oauth1.py:57
msgid "Access token is expired"
msgstr "Token de acesso expirou"

#: keystone/auth/plugins/oauth1.py:71
msgid "Could not validate the access token"
msgstr ""

#: keystone/auth/plugins/password.py:134
msgid "Invalid username or password"
msgstr "Nome de usuário ou senha inválidos"

#: keystone/catalog/controllers.py:165
#, python-format
msgid "Conflicting region IDs specified: \"%(url_id)s\" != \"%(ref_id)s\""
msgstr ""

#: keystone/catalog/core.py:56
#, python-format
msgid "Malformed endpoint - %(url)r is not a string"
msgstr ""

#: keystone/common/authorization.py:46 keystone/common/wsgi.py:60
#, python-format
msgid "token reference must be a KeystoneToken type, got: %s"
msgstr ""

#: keystone/common/authorization.py:54
msgid "RBAC: Invalid user data in token"
msgstr ""

#: keystone/common/base64utils.py:205 keystone/common/base64utils.py:278
#: keystone/common/base64utils.py:332
msgid "pad must be single character"
msgstr ""

#: keystone/common/base64utils.py:211
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before 2nd to last char"
msgstr ""

#: keystone/common/base64utils.py:215
#, python-format
msgid "text is multiple of 4, but pad \"%s\" occurs before non-pad last char"
msgstr ""

#: keystone/common/base64utils.py:221
#, python-format
msgid "text is not a multiple of 4, but contains pad \"%s\""
msgstr ""

#: keystone/common/base64utils.py:240 keystone/common/base64utils.py:261
msgid "padded base64url text must be multiple of 4 characters"
msgstr ""

#: keystone/common/controller.py:77 keystone/middleware/core.py:265
msgid "RBAC: Invalid token"
msgstr "RBAC: Token inválido"

#: keystone/common/controller.py:102 keystone/common/controller.py:199
#: keystone/common/controller.py:659
msgid "RBAC: Bypassing authorization"
msgstr "RBAC: Efetuando bypass da autorização"

#: keystone/common/controller.py:556
msgid "Cannot change Domain ID"
msgstr ""

#: keystone/common/controller.py:585
msgid "domain_id is required as part of entity"
msgstr ""

#: keystone/common/controller.py:588 keystone/common/controller.py:623
msgid "Invalid token found while getting domain ID for list request"
msgstr ""

#: keystone/common/controller.py:596
msgid "No domain information specified as part of list request"
msgstr ""

#: keystone/common/controller.py:620
msgid "A domain-scoped token must be used"
msgstr ""

#: keystone/common/dependency.py:87
msgid "event_callbacks must be a dict"
msgstr ""

#: keystone/common/dependency.py:92
#, python-format
msgid "event_callbacks[%s] must be a dict"
msgstr ""

#: keystone/common/pemutils.py:223
#, python-format
msgid "unknown pem_type \"%(pem_type)s\", valid types are: %(valid_pem_types)s"
msgstr ""

#: keystone/common/pemutils.py:242
#, python-format
msgid ""
"unknown pem header \"%(pem_header)s\", valid headers are: "
"%(valid_pem_headers)s"
msgstr ""

#: keystone/common/pemutils.py:298
#, python-format
msgid "failed to find end matching \"%s\""
msgstr ""

#: keystone/common/pemutils.py:302
#, python-format
msgid ""
"beginning & end PEM headers do not match (%(begin_pem_header)s!= "
"%(end_pem_header)s)"
msgstr ""

#: keystone/common/pemutils.py:377
#, python-format
msgid "unknown pem_type: \"%s\""
msgstr ""

#: keystone/common/pemutils.py:389
#, python-format
msgid ""
"failed to base64 decode %(pem_type)s PEM at position%(position)d: "
"%(err_msg)s"
msgstr ""

#: keystone/common/serializer.py:50
msgid "lxml is not installed."
msgstr ""

#: keystone/common/serializer.py:224
msgid "Multiple truncation attributes found"
msgstr ""

#: keystone/common/utils.py:98
#, python-format
msgid "Truncating user password to %d characters."
msgstr ""

#: keystone/common/utils.py:196 keystone/credential/controllers.py:43
msgid "Invalid blob in credential"
msgstr "BLOB inválido na credencial"

#: keystone/common/utils.py:275
msgid ""
"Error setting up the debug environment. Verify that the option --debug-"
"url has the format <host>:<port> and that a debugger processes is "
"listening on that port."
msgstr ""
"Erro configurando o ambiente de debug. Verifique que a opção --debug-url "
"possui o formato <host>:<port> e que o processo debugger está escutando "
"nesta porta."

#: keystone/common/wsgi.py:315
#, python-format
msgid "%s field is required and cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:327
#, python-format
msgid "%s field(s) cannot be empty"
msgstr ""

#: keystone/common/wsgi.py:544
msgid "The resource could not be found."
msgstr "O recurso não pôde ser localizado."

#: keystone/common/cache/_memcache_pool.py:100
#, python-format
msgid "Unable to get a connection from pool id %(id)s after %(seconds)s seconds."
msgstr ""

#: keystone/common/cache/core.py:101
#, python-format
msgid ""
"Unable to build cache config-key. Expected format \"<argname>:<value>\". "
"Skipping unknown format: %s"
msgstr ""
"Não é possível construir chave de configuração do cache. Formato esperado"
" \"<argname>:<value>\".  Pulando formato desconhecido: %s"

#: keystone/common/cache/core.py:133
msgid "region not type dogpile.cache.CacheRegion"
msgstr "região não é do tipo dogpile.cache.CacheRegion"

#: keystone/common/cache/backends/mongo.py:231
msgid "db_hosts value is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:236
msgid "database db_name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:241
msgid "cache_collection name is required"
msgstr ""

#: keystone/common/cache/backends/mongo.py:252
msgid "integer value expected for w (write concern attribute)"
msgstr ""

#: keystone/common/cache/backends/mongo.py:260
msgid "replicaset_name required when use_replica is True"
msgstr ""

#: keystone/common/cache/backends/mongo.py:275
msgid "integer value expected for mongo_ttl_seconds"
msgstr ""

#: keystone/common/cache/backends/mongo.py:301
msgid "no ssl support available"
msgstr ""

#: keystone/common/cache/backends/mongo.py:310
#, python-format
msgid ""
"Invalid ssl_cert_reqs value of %s, must be one of \"NONE\", \"OPTIONAL\","
" \"REQUIRED\""
msgstr ""

#: keystone/common/cache/backends/mongo.py:403
#, python-format
msgid ""
"TTL index already exists on db collection <%(c_name)s>, remove index "
"<%(indx_name)s> first to make updated mongo_ttl_seconds value to be  "
"effective"
msgstr ""

#: keystone/common/environment/eventlet_server.py:187
msgid "Server error"
msgstr "Erro do Servidor"

#: keystone/common/kvs/core.py:71
#, python-format
msgid "Lock Timeout occurred for key, %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:106
#, python-format
msgid "KVS region %s is already configured. Cannot reconfigure."
msgstr ""

#: keystone/common/kvs/core.py:145
#, python-format
msgid "Key Value Store not configured: %s"
msgstr ""

#: keystone/common/kvs/core.py:198
msgid "`key_mangler` option must be a function reference"
msgstr ""

#: keystone/common/kvs/core.py:352
#, python-format
msgid "Lock key must match target key: %(lock)s != %(target)s"
msgstr ""

#: keystone/common/kvs/core.py:356
msgid "Must be called within an active lock context."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:73
#, python-format
msgid "Maximum lock attempts on %s occurred."
msgstr ""

#: keystone/common/kvs/backends/memcached.py:112
#, python-format
msgid ""
"Backend `%(driver)s` is not a valid memcached backend. Valid drivers: "
"%(driver_list)s"
msgstr ""

#: keystone/common/kvs/backends/memcached.py:183
msgid "`key_mangler` functions must be callable."
msgstr ""

#: keystone/common/ldap/core.py:186
#, python-format
msgid "Invalid LDAP deref option: %(option)s. Choose one of: %(options)s"
msgstr ""

#: keystone/common/ldap/core.py:196
#, python-format
msgid "Invalid LDAP TLS certs option: %(option)s. Choose one of: %(options)s"
msgstr ""
"Opção de certificado LADP TLS inválida: %(option)s. Escolha uma de: "
"%(options)s"

#: keystone/common/ldap/core.py:208
#, python-format
msgid "Invalid LDAP scope: %(scope)s. Choose one of: %(options)s"
msgstr "Escopo LDAP inválido: %(scope)s. Escolha um de: %(options)s"

#: keystone/common/ldap/core.py:583
msgid "Invalid TLS / LDAPS combination"
msgstr "Combinação TLS / LADPS inválida"

#: keystone/common/ldap/core.py:588
#, python-format
msgid "Invalid LDAP TLS_AVAIL option: %s. TLS not available"
msgstr "Opção LDAP TLS_AVAIL inválida: %s. TLS não dsponível"

#: keystone/common/ldap/core.py:598
#, python-format
msgid "tls_cacertfile %s not found or is not a file"
msgstr "tls_cacertfile %s não encontrada ou não é um arquivo"

#: keystone/common/ldap/core.py:610
#, python-format
msgid "tls_cacertdir %s not found or is not a directory"
msgstr "tls_cacertdir %s não encontrado ou não é um diretório"

#: keystone/common/ldap/core.py:1303
#, python-format
msgid "ID attribute %(id_attr)s not found in LDAP object %(dn)s"
msgstr ""

#: keystone/common/ldap/core.py:1347
#, python-format
msgid "LDAP %s create"
msgstr "Criação de LDAP %s"

#: keystone/common/ldap/core.py:1352
#, python-format
msgid "LDAP %s update"
msgstr "Atualização de LDAP %s"

#: keystone/common/ldap/core.py:1357
#, python-format
msgid "LDAP %s delete"
msgstr "Exclusão de LDAP %s"

#: keystone/common/ldap/core.py:1499
#, python-format
msgid "Cannot change %(option_name)s %(attr)s"
msgstr "Não é possível alterar %(option_name)s %(attr)s"

#: keystone/common/ldap/core.py:1586
#, python-format
msgid "Member %(member)s is already a member of group %(group)s"
msgstr ""

#: keystone/common/ldap/core.py:1635
#, python-format
msgid ""
"When deleting entries for %(search_base)s, could not delete nonexistent "
"entries %(entries)s%(dots)s"
msgstr ""

#: keystone/common/sql/core.py:219
msgid ""
"Cannot truncate a driver call without hints list as first parameter after"
" self "
msgstr ""

#: keystone/common/sql/core.py:401
msgid "Duplicate Entry"
msgstr ""

#: keystone/common/sql/core.py:417
#, python-format
msgid "An unexpected error occurred when trying to store %s"
msgstr ""

#: keystone/common/sql/migration_helpers.py:184
#: keystone/common/sql/migration_helpers.py:223
#, python-format
msgid "%s extension does not exist."
msgstr ""

#: keystone/common/validation/validators.py:54
#, python-format
msgid "Invalid input for field '%(path)s'. The value is '%(value)s'."
msgstr ""

#: keystone/contrib/ec2/controllers.py:318
msgid "Token belongs to another user"
msgstr "O token pertence à outro usuário"

#: keystone/contrib/ec2/controllers.py:346
msgid "Credential belongs to another user"
msgstr "A credencial pertence à outro usuário"

#: keystone/contrib/endpoint_filter/backends/sql.py:69
#, python-format
msgid "Endpoint %(endpoint_id)s not found in project %(project_id)s"
msgstr "Endpoint %(endpoint_id)s não encontrado no projeto %(project_id)s"

#: keystone/contrib/endpoint_filter/backends/sql.py:180
msgid "Endpoint Group Project Association not found"
msgstr ""

#: keystone/contrib/endpoint_policy/core.py:258
#, python-format
msgid "No policy is associated with endpoint %(endpoint_id)s."
msgstr ""

#: keystone/contrib/example/core.py:64 keystone/contrib/example/core.py:73
#, python-format
msgid ""
"Received the following notification: service %(service)s, resource_type: "
"%(resource_type)s, operation %(operation)s payload %(payload)s"
msgstr ""

#: keystone/contrib/federation/controllers.py:279
msgid "Use a project scoped token when attempting tocreate a SAML assertion"
msgstr ""

#: keystone/contrib/federation/idp.py:449
#, python-format
msgid "Cannot open certificate %(cert_file)s. Reason: %(reason)s"
msgstr ""

#: keystone/contrib/federation/idp.py:516
msgid "Ensure configuration option idp_entity_id is set."
msgstr ""

#: keystone/contrib/federation/idp.py:519
msgid "Ensure configuration option idp_sso_endpoint is set."
msgstr ""

#: keystone/contrib/federation/idp.py:539
msgid ""
"idp_contact_type must be one of: [technical, other, support, "
"administrative or billing."
msgstr ""

#: keystone/contrib/federation/utils.py:122
msgid "Federation token is expired"
msgstr ""

#: keystone/contrib/federation/utils.py:225
msgid "Could not map user"
msgstr ""

#: keystone/contrib/federation/utils.py:254
#, python-format
msgid "Ignoring user name %s"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:96
msgid "Cannot change consumer secret"
msgstr "Não é possível alterar segredo do consumidor"

#: keystone/contrib/oauth1/controllers.py:128
msgid "Cannot list request tokens with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:188
#: keystone/contrib/oauth1/backends/sql.py:267
msgid "User IDs do not match"
msgstr "ID de usuário não confere"

#: keystone/contrib/oauth1/controllers.py:195
msgid "Could not find role"
msgstr "Não é possível encontrar role"

#: keystone/contrib/oauth1/controllers.py:238
msgid "Invalid signature"
msgstr ""

#: keystone/contrib/oauth1/controllers.py:287
#: keystone/contrib/oauth1/controllers.py:363
msgid "Request token is expired"
msgstr "Token de requisição expirou"

#: keystone/contrib/oauth1/controllers.py:301
msgid "There should not be any non-oauth parameters"
msgstr "Não deve haver nenhum parâmetro não oauth"

#: keystone/contrib/oauth1/controllers.py:305
msgid "provided consumer key does not match stored consumer key"
msgstr ""
"Chave de consumidor fornecida não confere com a chave de consumidor "
"armazenada"

#: keystone/contrib/oauth1/controllers.py:309
msgid "provided verifier does not match stored verifier"
msgstr "Verificador fornecido não confere com o verificador armazenado"

#: keystone/contrib/oauth1/controllers.py:313
msgid "provided request key does not match stored request key"
msgstr ""
"Chave de requisição do provedor não confere com a chave de requisição "
"armazenada"

#: keystone/contrib/oauth1/controllers.py:317
msgid "Request Token does not have an authorizing user id"
msgstr "Token de Requisição não possui um ID de usuário autorizado"

#: keystone/contrib/oauth1/controllers.py:352
msgid "Cannot authorize a request token with a token issued via delegation."
msgstr ""

#: keystone/contrib/oauth1/controllers.py:382
msgid "authorizing user does not have role required"
msgstr "Usuário autorizado não possui o role necessário"

#: keystone/contrib/oauth1/controllers.py:395
msgid "User is not a member of the requested project"
msgstr "Usuário não é um membro do projeto requisitado"

#: keystone/contrib/oauth1/backends/sql.py:88
msgid "Consumer not found"
msgstr "Consumidor não encontrado"

#: keystone/contrib/oauth1/backends/sql.py:183
msgid "Request token not found"
msgstr "Token de requisição não encontrado"

#: keystone/contrib/oauth1/backends/sql.py:247
msgid "Access token not found"
msgstr "Token de acesso não encontrado"

#: keystone/contrib/revoke/controllers.py:33
#, python-format
msgid "invalid date format %s"
msgstr ""

#: keystone/contrib/revoke/core.py:152
msgid ""
"The revoke call must not have both domain_id and project_id. This is a "
"bug in the Keystone server. The current request is aborted."
msgstr ""

#: keystone/contrib/revoke/core.py:221 keystone/token/provider.py:234
#: keystone/token/provider.py:256 keystone/token/provider.py:354
#: keystone/token/provider.py:361 keystone/token/providers/common.py:576
msgid "Failed to validate token"
msgstr "Falha ao validar token"

#: keystone/identity/controllers.py:70
msgid "Enabled field must be a boolean"
msgstr "Campo habilitado precisa ser um booleano"

#: keystone/identity/controllers.py:96
msgid "Enabled field should be a boolean"
msgstr "Campo habilitado deve ser um booleano"

#: keystone/identity/controllers.py:137
#, python-format
msgid "Unable to remove user %(user)s from %(tenant)s."
msgstr "Não é possível remover usuário %(user)s de %(tenant)s."

#: keystone/identity/controllers.py:156
#, python-format
msgid "Unable to add user %(user)s to %(tenant)s."
msgstr "Não é possível adicionar usuário %(user)s em %(tenant)s."

#: keystone/identity/core.py:118
#, python-format
msgid "Invalid domain name (%s) found in config file name"
msgstr ""
"nome de domínio inválido (%s) encontrado no nome do arquivo de "
"configuração"

#: keystone/identity/core.py:144
#, python-format
msgid "Unable to locate domain config directory: %s"
msgstr "Não é possível localizar diretório de configuração de domínio: %s"

#: keystone/identity/core.py:220 keystone/identity/backends/kvs.py:75
#: keystone/identity/backends/kvs.py:77 keystone/identity/backends/ldap.py:59
#: keystone/identity/backends/ldap.py:61 keystone/identity/backends/ldap.py:67
#: keystone/identity/backends/ldap.py:69 keystone/identity/backends/sql.py:112
#: keystone/identity/backends/sql.py:114
msgid "Invalid user / password"
msgstr ""

#: keystone/identity/core.py:594 keystone/token/core.py:64
#, python-format
msgid "User is disabled: %s"
msgstr "O usuário está desativado: %s"

#: keystone/identity/core.py:636
msgid "Cannot change user ID"
msgstr ""

#: keystone/identity/backends/kvs.py:179 keystone/identity/backends/kvs.py:188
msgid "User not found in group"
msgstr "Usuário não localizado no grupo"

#: keystone/identity/backends/ldap.py:99
msgid "Cannot change user name"
msgstr ""

#: keystone/identity/backends/ldap.py:183 keystone/identity/backends/sql.py:196
#: keystone/identity/backends/sql.py:214
#, python-format
msgid "User '%(user_id)s' not found in group '%(group_id)s'"
msgstr ""

#: keystone/identity/backends/ldap.py:337
#, python-format
msgid "User %(user_id)s is already a member of group %(group_id)s"
msgstr "Usuário %(user_id)s já é membro do grupo %(group_id)s"

#: keystone/middleware/core.py:275
msgid "Auth context already exists in the request environment"
msgstr ""

#: keystone/models/token_model.py:61
msgid "Found invalid token: scoped to both project and domain."
msgstr ""

#: keystone/openstack/common/gettextutils.py:301
msgid "Message objects do not support addition."
msgstr ""

#: keystone/openstack/common/gettextutils.py:311
msgid ""
"Message objects do not support str() because they may contain non-ascii "
"characters. Please use unicode() or translate() instead."
msgstr ""

#: keystone/openstack/common/log.py:290
#, python-format
msgid "Deprecated: %s"
msgstr "Deprecado: %s"

#: keystone/openstack/common/log.py:398
#, python-format
msgid "Error loading logging config %(log_config)s: %(err_msg)s"
msgstr "Erro carregando configuração de logging: %(log_config)s: %(err_msg)s"

#: keystone/openstack/common/log.py:459
#, python-format
msgid "syslog facility must be one of: %s"
msgstr "Recurso syslog deve ser um destes: %s"

#: keystone/openstack/common/log.py:710
#, python-format
msgid "Fatal call to deprecated config: %(msg)s"
msgstr "Chamada fatal à configuração deprecada: %(msg)s"

#: keystone/openstack/common/policy.py:96
msgid "The JSON file that defines policies."
msgstr ""

#: keystone/openstack/common/policy.py:99
msgid "Default rule. Enforced when a requested rule is not found."
msgstr ""

#: keystone/openstack/common/policy.py:114
#, python-format
msgid "Policy doesn't allow %s to be performed."
msgstr "Política não permite a realização de %s."

#: keystone/openstack/common/policy.py:208
#, python-format
msgid "Rules must be an instance of dict or Rules, got %s instead"
msgstr "Regras devem ser uma instância de dict ou Rules, recebeu %s em seu lugar"

#: keystone/openstack/common/processutils.py:59
msgid "Unexpected error while running command."
msgstr ""

#: keystone/openstack/common/processutils.py:62
#, python-format
msgid ""
"%(description)s\n"
"Command: %(cmd)s\n"
"Exit code: %(exit_code)s\n"
"Stdout: %(stdout)r\n"
"Stderr: %(stderr)r"
msgstr ""

#: keystone/openstack/common/processutils.py:143
#, python-format
msgid "Got unknown keyword args: %r"
msgstr ""

#: keystone/openstack/common/processutils.py:148
msgid "Command requested root, but did not specify a root helper."
msgstr ""

#: keystone/openstack/common/processutils.py:158
#, python-format
msgid "Running cmd (subprocess): %s"
msgstr ""

#: keystone/openstack/common/processutils.py:206
#, python-format
msgid "%r failed. Retrying."
msgstr ""

#: keystone/openstack/common/processutils.py:248
msgid "Environment not supported over SSH"
msgstr ""

#: keystone/openstack/common/processutils.py:252
msgid "process_input not supported over SSH"
msgstr ""

#: keystone/openstack/common/strutils.py:114
#, python-format
msgid "Unrecognized value '%(val)s', acceptable values are: %(acceptable)s"
msgstr "Valor desconhecido '%(val)s', valores aceitáveis são: %(acceptable)s"

#: keystone/openstack/common/strutils.py:219
#, python-format
msgid "Invalid unit system: \"%s\""
msgstr ""

#: keystone/openstack/common/strutils.py:228
#, python-format
msgid "Invalid string format: %s"
msgstr "formato de string inválido: %s"

#: keystone/openstack/common/versionutils.py:90
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s and "
"may be removed in %(remove_in)s."
msgstr ""
"%(what)s está deprecado desde %(as_of)s em favor de %(in_favor_of)s e "
"pode ser removido em %(remove_in)s."

#: keystone/openstack/common/versionutils.py:94
#, python-format
msgid ""
"%(what)s is deprecated as of %(as_of)s and may be removed in "
"%(remove_in)s. It will not be superseded."
msgstr ""
"%(what)s está deprecado desde %(as_of)s e pode ser removido em "
"%(remove_in)s. Ele não será substituído."

#: keystone/openstack/common/versionutils.py:98
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s in favor of %(in_favor_of)s."
msgstr ""

#: keystone/openstack/common/versionutils.py:101
#, python-format
msgid "%(what)s is deprecated as of %(as_of)s. It will not be superseded."
msgstr ""

#: keystone/tests/core.py:146
#, python-format
msgid "Failed to checkout %s"
msgstr "Falha ao fazer check out %s"

#: keystone/token/controllers.py:391
#, python-format
msgid "User %(u_id)s is unauthorized for tenant %(t_id)s"
msgstr "Usuário %(u_id)s  não está autorizado para o tenant %(t_id)s"

#: keystone/token/controllers.py:410 keystone/token/controllers.py:413
msgid "Token does not belong to specified tenant."
msgstr "O token não pertence ao tenant especificado."

#: keystone/token/core.py:79
#, python-format
msgid "Tenant is disabled: %s"
msgstr ""

#: keystone/token/provider.py:134
msgid ""
"[signing] token_format is deprecated. Please change to setting the "
"[token] provider configuration value instead"
msgstr ""

#: keystone/token/provider.py:142
msgid ""
"Unrecognized keystone.conf [signing] token_format: expected either 'UUID'"
" or 'PKI'"
msgstr ""
"keystone.conf não reconhecido [assinando] token_format: esperado 'UUID' "
"ou 'PKI'"

#: keystone/token/provider.py:352
#, python-format
msgid "Unexpected error or malformed token determining token expiry: %s"
msgstr "Erro inesperado ou token mal formado ao determinar validade do token: %s"

#: keystone/token/persistence/backends/kvs.py:57
msgid ""
"It is recommended to only use the base key-value-store implementation for"
" the token driver for testing purposes.  Please use "
"keystone.token.backends.memcache.Token or "
"keystone.token.backends.sql.Token instead."
msgstr ""

#: keystone/token/persistence/backends/kvs.py:132
#, python-format
msgid "Unknown token version %s"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:205
#, python-format
msgid "Token `%s` is expired, not adding to the revocation list."
msgstr ""

#: keystone/token/persistence/backends/kvs.py:225
#, python-format
msgid ""
"Reinitializing revocation list due to error in loading revocation list "
"from backend.  Expected `list` type got `%(type)s`. Old revocation list "
"data: %(list)r"
msgstr ""

#: keystone/token/persistence/backends/kvs.py:239
#, python-format
msgid ""
"Removing `%s` from revocation list due to invalid expires data in "
"revocation list."
msgstr ""

#: keystone/token/providers/common.py:195
#: keystone/token/providers/common.py:300
#, python-format
msgid "User %(user_id)s has no access to project %(project_id)s"
msgstr "O usuário %(user_id)s não tem acesso ao projeto %(project_id)s"

#: keystone/token/providers/common.py:200
#: keystone/token/providers/common.py:305
#, python-format
msgid "User %(user_id)s has no access to domain %(domain_id)s"
msgstr "O usuário %(user_id)s não tem acesso ao domínio %(domain_id)s"

#: keystone/token/providers/common.py:227
msgid "Trustor is disabled."
msgstr "O fiador está desativado."

#: keystone/token/providers/common.py:291
msgid "Trustee has no delegated roles."
msgstr "Fiador não possui roles delegados."

#: keystone/token/providers/common.py:344
#, python-format
msgid "Invalid audit info data type: %(data)s (%(type)s)"
msgstr ""

#: keystone/token/providers/common.py:365
msgid "User is not a trustee."
msgstr "Usuário não é confiável."

#: keystone/token/providers/common.py:442
msgid "Oauth is disabled."
msgstr "Oauth está desabilitado."

#: keystone/token/providers/common.py:499
msgid "Non-default domain is not supported"
msgstr "O domínio não padrão não é suportado"

#: keystone/token/providers/common.py:507
msgid "Domain scoped token is not supported"
msgstr "O token de escopo de domínio não é suportado"

#: keystone/token/providers/pki.py:45
msgid "Unable to sign token"
msgstr ""

#: keystone/token/providers/pki.py:46 keystone/token/providers/pkiz.py:29
msgid "Unable to sign token."
msgstr "Não é possível assinar o token."

#: keystone/trust/controllers.py:135
msgid "Cannot create a trust with a token issued via delegation."
msgstr ""

#: keystone/trust/controllers.py:162
msgid "The authenticated user should match the trustor."
msgstr ""

#: keystone/trust/controllers.py:167
msgid "At least one role should be specified."
msgstr ""

#: keystone/trust/core.py:58
msgid "remaining_uses must be a positive integer or null."
msgstr ""

